[package]
name = "dpdk-wrapper"
version = "0.1.0"
edition = "2021"

[dependencies]
color-eyre = "0.5"
tracing = "0.1"
byteorder = "1"
eui48 = "1"
yaml-rust = "0.4"
ahash = "0.7"

[build-dependencies]
bindgen = "0.59"
cc = "1"

[dev-dependencies]
tracing-subscriber = "0.3"
